/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Album.as).
 */

package org.granite.tide.test.domain.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class AlbumBase implements IExternalizable {

        private var _albumTracks:ListCollectionView;
        private var _duration:Duration;
        private var _id:Number;
        private var _name:String;
        private var _year:int;

        public function set albumTracks(value:ListCollectionView):void {
            _albumTracks = value;
        }
        public function get albumTracks():ListCollectionView {
            return _albumTracks;
        }

        public function set duration(value:Duration):void {
            _duration = value;
        }
        public function get duration():Duration {
            return _duration;
        }

        public function set id(value:Number):void {
            _id = value;
        }
        public function get id():Number {
            return _id;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set year(value:int):void {
            _year = value;
        }
        public function get year():int {
            return _year;
        }

        public function readExternal(input:IDataInput):void {
            _albumTracks = input.readObject() as ListCollectionView;
            _duration = input.readObject() as Duration;
            _id = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _name = input.readObject() as String;
            _year = input.readObject() as int;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_albumTracks);
            output.writeObject(_duration);
            output.writeObject(_id);
            output.writeObject(_name);
            output.writeObject(_year);
        }
    }
}