/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.granite.tide.test.domain.model {

    [Bindable]
    [RemoteClass(alias="org.granite.tide.test.domain.model.Track")]
    public class Track extends TrackBase {
    }
}